extends: eslint:recommended
parserOptions:
  sourceType: module
env:
  es6: true
  node: true
rules:
  max-len:
    - error
    - code: 140
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
